### ISSUE TITLE
About voxelize 3D model using prisms

### ISSUE THREAD

**Issue by hanfengsunshine** [mattatz/unity-voxel#2]
Hi, you have done great work on creating voxelization models.

    A little question: the basic units of the model is the cubes, how to change the cubes into triangles prisms?  

   Like the attached documents: 

Thank you! 
![voxelize a model using triangle prisms](https://user-images.githubusercontent.com/14012055/35311509-cdcf04b4-00f1-11e8-8cd1-9cbdfaf018f7.jpg)

**Comment by mattatz** [comment]
@hanfengsunshine 
How about replace cube to prism for rendering voxels in GPUVoxelParticleSystem ?
